FROM golang:alpine as builder
WORKDIR /src/todos-cli
COPY . .
RUN apk update && apk add git
RUN go get -u github.com/spf13/cobra
RUN go get -u github.com/spf13/viper
RUN apk del git
ENTRYPOINT ["go", "run", "main.go"]