version: "3.7"

services:
    postgres:
        environment:
            POSTGRES_USER: ''
            POSTGRES_PASSWORD: ''
        image: localhost:5000/postgres:latest
        container_name: postgres_container
        ports:
            - 5432:5432
    
    buildit:
        environment:
            postgresConnectionString: dbname=buildit host=postgres_container password=postgres user=postgres sslmode=disable port=5432
            apiUrl: http://buildit:8081
            customerId: customer-2
            kafkaUrl: kafka:9092
        image: localhost:5000/buildit:latest
        ports: 
            - 8081:8081
        container_name: buildit_container
        depends_on: 
            - postgres
            - kafka

    kafka:
        image: wurstmeister/kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CONNECT_BOOTSTRAP_SERVERS=localhost:9092
            - KAFKA_CONNECT_REST_PORT=8082
            - KAFKA_CONNECT_REST_ADVERTISED_HOST_NAME="kafka"
            - KAFKA_CONNECT_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
            - KAFKA_CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
            - KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=0
            - KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=0
            - KAFKA_CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
            - KAFKA_CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
            - KAFKA_CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE=0
            - KAFKA_CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE=0
            - KAFKA_CONNECT_OFFSET_STORAGE_FILE_FILENAME="/tmp/connect.offsets"
            # Flush much faster than normal, which is useful for testing/debugging
            - KAFKA_CONNECT_OFFSET_FLUSH_INTERVAL_MS=1000
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
            - LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER=DEBUG
            - GROUP_ID=1
            - KAFKA_CREATE_TOPICS=unpaidInvoices:1:1 # topic:partition:replicas
        depends_on:
        - zookeeper
        ports:
        - '9092:9092'
        - '8082:8082'
        - '8083:8083'

    zookeeper:
        hostname: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        expose:
        - "2181"
        ports:
        - "2181:2181"
