// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: pkg/transport/gRPC/gRPCService.proto

package grpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PlantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlantsRequest) Reset() {
	*x = PlantsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantsRequest) ProtoMessage() {}

func (x *PlantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantsRequest.ProtoReflect.Descriptor instead.
func (*PlantsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP(), []int{0}
}

type Plant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	PricePerDay float64 `protobuf:"fixed64,4,opt,name=PricePerDay,proto3" json:"PricePerDay,omitempty"`
}

func (x *Plant) Reset() {
	*x = Plant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP(), []int{1}
}

func (x *Plant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Plant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Plant) GetPricePerDay() float64 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

type PlantsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Plant `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PlantsResponse) Reset() {
	*x = PlantsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantsResponse) ProtoMessage() {}

func (x *PlantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantsResponse.ProtoReflect.Descriptor instead.
func (*PlantsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP(), []int{2}
}

func (x *PlantsResponse) GetItems() []*Plant {
	if x != nil {
		return x.Items
	}
	return nil
}

type PlantPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	StartDate string `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   string `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *PlantPriceRequest) Reset() {
	*x = PlantPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantPriceRequest) ProtoMessage() {}

func (x *PlantPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantPriceRequest.ProtoReflect.Descriptor instead.
func (*PlantPriceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP(), []int{3}
}

func (x *PlantPriceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlantPriceRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *PlantPriceRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type PlantPrice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlantId          int64   `protobuf:"varint,1,opt,name=PlantId,proto3" json:"PlantId,omitempty"`
	StartDate        string  `protobuf:"bytes,2,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	EndDate          string  `protobuf:"bytes,3,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	PricePerDuration float64 `protobuf:"fixed64,4,opt,name=PricePerDuration,proto3" json:"PricePerDuration,omitempty"`
}

func (x *PlantPrice) Reset() {
	*x = PlantPrice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantPrice) ProtoMessage() {}

func (x *PlantPrice) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantPrice.ProtoReflect.Descriptor instead.
func (*PlantPrice) Descriptor() ([]byte, []int) {
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP(), []int{4}
}

func (x *PlantPrice) GetPlantId() int64 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

func (x *PlantPrice) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *PlantPrice) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *PlantPrice) GetPricePerDuration() float64 {
	if x != nil {
		return x.PricePerDuration
	}
	return 0
}

type PlantPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *PlantPrice `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *PlantPriceResponse) Reset() {
	*x = PlantPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantPriceResponse) ProtoMessage() {}

func (x *PlantPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantPriceResponse.ProtoReflect.Descriptor instead.
func (*PlantPriceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP(), []int{5}
}

func (x *PlantPriceResponse) GetItem() *PlantPrice {
	if x != nil {
		return x.Item
	}
	return nil
}

type PlantAvailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	StartDate string `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   string `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *PlantAvailabilityRequest) Reset() {
	*x = PlantAvailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantAvailabilityRequest) ProtoMessage() {}

func (x *PlantAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*PlantAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP(), []int{6}
}

func (x *PlantAvailabilityRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlantAvailabilityRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *PlantAvailabilityRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type PlantAvailabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAvailable bool `protobuf:"varint,1,opt,name=isAvailable,proto3" json:"isAvailable,omitempty"`
}

func (x *PlantAvailabilityResponse) Reset() {
	*x = PlantAvailabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantAvailabilityResponse) ProtoMessage() {}

func (x *PlantAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_gRPC_gRPCService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*PlantAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP(), []int{7}
}

func (x *PlantAvailabilityResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_pkg_transport_gRPC_gRPCService_proto protoreflect.FileDescriptor

var file_pkg_transport_gRPC_gRPCService_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x67, 0x52, 0x50, 0x43, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x0f, 0x0a, 0x0d,
	0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6f, 0x0a,
	0x05, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x44, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x44, 0x61, 0x79, 0x22, 0x33,
	0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x5b, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65,
	0x22, 0x8a, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x2a, 0x0a, 0x10, 0x50, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x50, 0x65, 0x72, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x0a,
	0x12, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x62, 0x0a, 0x18, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x3d, 0x0a,
	0x19, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x69, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x32, 0xe7, 0x01, 0x0a,
	0x0b, 0x67, 0x52, 0x50, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x13, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x55, 0x0a, 0x10, 0x49, 0x73, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_transport_gRPC_gRPCService_proto_rawDescOnce sync.Once
	file_pkg_transport_gRPC_gRPCService_proto_rawDescData = file_pkg_transport_gRPC_gRPCService_proto_rawDesc
)

func file_pkg_transport_gRPC_gRPCService_proto_rawDescGZIP() []byte {
	file_pkg_transport_gRPC_gRPCService_proto_rawDescOnce.Do(func() {
		file_pkg_transport_gRPC_gRPCService_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_transport_gRPC_gRPCService_proto_rawDescData)
	})
	return file_pkg_transport_gRPC_gRPCService_proto_rawDescData
}

var file_pkg_transport_gRPC_gRPCService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_transport_gRPC_gRPCService_proto_goTypes = []interface{}{
	(*PlantsRequest)(nil),             // 0: grpc.PlantsRequest
	(*Plant)(nil),                     // 1: grpc.Plant
	(*PlantsResponse)(nil),            // 2: grpc.PlantsResponse
	(*PlantPriceRequest)(nil),         // 3: grpc.PlantPriceRequest
	(*PlantPrice)(nil),                // 4: grpc.PlantPrice
	(*PlantPriceResponse)(nil),        // 5: grpc.PlantPriceResponse
	(*PlantAvailabilityRequest)(nil),  // 6: grpc.PlantAvailabilityRequest
	(*PlantAvailabilityResponse)(nil), // 7: grpc.PlantAvailabilityResponse
}
var file_pkg_transport_gRPC_gRPCService_proto_depIdxs = []int32{
	1, // 0: grpc.PlantsResponse.items:type_name -> grpc.Plant
	4, // 1: grpc.PlantPriceResponse.item:type_name -> grpc.PlantPrice
	0, // 2: grpc.gRPCService.GetAllPlants:input_type -> grpc.PlantsRequest
	3, // 3: grpc.gRPCService.GetPlantPrice:input_type -> grpc.PlantPriceRequest
	6, // 4: grpc.gRPCService.IsPlantAvailable:input_type -> grpc.PlantAvailabilityRequest
	2, // 5: grpc.gRPCService.GetAllPlants:output_type -> grpc.PlantsResponse
	5, // 6: grpc.gRPCService.GetPlantPrice:output_type -> grpc.PlantPriceResponse
	7, // 7: grpc.gRPCService.IsPlantAvailable:output_type -> grpc.PlantAvailabilityResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_transport_gRPC_gRPCService_proto_init() }
func file_pkg_transport_gRPC_gRPCService_proto_init() {
	if File_pkg_transport_gRPC_gRPCService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_transport_gRPC_gRPCService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_transport_gRPC_gRPCService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_transport_gRPC_gRPCService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_transport_gRPC_gRPCService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_transport_gRPC_gRPCService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantPrice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_transport_gRPC_gRPCService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_transport_gRPC_gRPCService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantAvailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_transport_gRPC_gRPCService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantAvailabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_transport_gRPC_gRPCService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_transport_gRPC_gRPCService_proto_goTypes,
		DependencyIndexes: file_pkg_transport_gRPC_gRPCService_proto_depIdxs,
		MessageInfos:      file_pkg_transport_gRPC_gRPCService_proto_msgTypes,
	}.Build()
	File_pkg_transport_gRPC_gRPCService_proto = out.File
	file_pkg_transport_gRPC_gRPCService_proto_rawDesc = nil
	file_pkg_transport_gRPC_gRPCService_proto_goTypes = nil
	file_pkg_transport_gRPC_gRPCService_proto_depIdxs = nil
}
