FROM golang:alpine as builder
WORKDIR src/esi-homework1-backend
COPY . .
EXPOSE 8000
RUN apk update && apk add git
RUN go get -u github.com/gorilla/mux
RUN apk del git
ENTRYPOINT ["go", "run", "main.go"]
